experiment_name: n_shots
model_name: core_vae_nano
lr: 0.0001
lr_scheduler: reduce_on_plateau
batch_size: 16
epochs: 500
vis_val: True
downstream_task: pretraining
input_channels: 10
input_size: 128
output_channels: 1
regions: null
n_shot: null
split_ratio: 0.1
augmentations: False
early_stop: 15
warmup: False
device: cuda
num_workers: 8
pretrained_model_path:
freeze_pretrained: True
