experiment_name: 281123_n_shots
model_name: SatMAE_classifier
lr: 0.0001
lr_scheduler: reduce_on_plateau
batch_size: 16
epochs: 500
vis_val: True
downstream_task: lc_classification
input_channels: 10
input_size: 128
output_channels: 11
regions: null
n_shot: 50
split_ratio: null
augmentations: True
early_stop: 15
warmup: False
device: cuda
num_workers: 16
pretrained_model_path:
freeze_pretrained:
