experiment_name: test_first
model_name: baseline_cnn
lr: 0.0001
lr_scheduler: null
batch_size: 32
epochs: 1
vis_val: True
downstream_task: lc
input_channels: 10
input_size: 128
output_channels: 11
regions: null
n_shot: 50
split_ratio: null
augmentations: False
early_stop: 50
warmup: False
device: cuda:0
num_workers: 6


# python training_script.py [--experiment_name EXPERIMENT_NAME] --model_name
#                           {baseline_cnn,core_unet_base,core_unet_large,core_unet_huge,mixer_base,mixer_large,mixer_huge,linear_vit_base,linear_vit_larger,linear_vit_huge,autoencoder_vit_base,autoencoder_vit_large,autoencoder_vit_huge}
#                           [--lr LR] [--batch_size BATCH_SIZE] [--epochs EPOCHS] [--early_stop EARLY_STOP] [--lr_scheduler {None,reduce_on_plateau,cosine_annealing}] [--warmup] [--device DEVICE] [--num_workers NUM_WORKERS]
#                           [--vis_val] --downstream_task {roads,building,lc} [--input_channels INPUT_CHANNELS] --input_size INPUT_SIZE --output_channels OUTPUT_CHANNELS
#                           [--regions {None,denmark-1,denmark-2,east-africa,egypt-1,eq-guinea,europe,ghana-1,isreal-1,isreal-2,japan,nigeria,north-america,senegal,south-america,tanzania-1,tanzania-2,tanzania-3,tanzania-4,tanzania-5,uganda-1}]
#                           [--n_shot N_SHOT] [--split_ratio SPLIT_RATIO] [--augmentations]