experiment_name: tests
model_name: core_unet_nano
lr: 0.0001
lr_scheduler: reduce_on_plateau
batch_size: 256
epochs: 500
vis_val: True
downstream_task: lc
input_channels: 10
input_size: 128
output_channels: 11
regions:
n_shot: null
split_ratio: 1.0
augmentations: True
early_stop: 15
warmup: False
device: cuda
num_workers: 24
pretrained_model_path:
freeze_pretrained:
