experiment_name: n_shots
model_name: baseline_cnn
lr: 0.0001
lr_scheduler: reduce_on_plateau
batch_size: 16
epochs: 100
vis_val: True
downstream_task: building
input_channels: 10
input_size: 128
output_channels: 1
regions: null
n_shot: 50
split_ratio: null
augmentations: True
early_stop: 10
warmup: False
device: cuda
num_workers: 6
pretrained_model_path: null
freeze_pretrained: False
