experiment_name: nshot_experiments_eo-hpc
model_name: core_unet_nano
lr: 0.0001
lr_scheduler: reduce_on_plateau
batch_size: 64
epochs: 500
vis_val: True
downstream_task: lc
input_channels: 10
input_size: 128
output_channels: 11
regions:
n_shot: 50
split_ratio: null
augmentations: True
early_stop: 15
warmup: False
device: cuda
num_workers: 24
pretrained_model_path:
freeze_pretrained:
data_path_128_10m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np/
data_path_224_10m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np_224/
data_path_224_30m: /home/phimultigpu/phileo_NFS/phileo_data/downstream/downstream_dataset_patches_np_HLS/