regions = {'north-america':0,'japan':1, 'east-africa':2, 'europe':3,'eq-guinea':4,'south-america':5, 'nigeria':6, 'senegal':7}
region_inv = {v:k for k,v in zip(regions.keys(),regions.values())}

# feature_positions_predictions = {'kg': [i for i in range(31)], 'coords':[31,32,33], 'region':[j for j in range(34,34+len(regions))]}
# feature_positions_label = {'pre_aug':{'kg': [i for i in range(31)], 'coords':[31,32], 'region':[33]}, 'post_aug':{'kg': [i for i in range(31)], 'coords':[31,32,33], 'region':[34]}}

feature_positions_predictions = {'kg': [i for i in range(31)], 'coords':[31,32,33], 'time':[34,35]}
feature_positions_label = {'kg': [i for i in range(31)], 'coords':[31,32,33], 'time':[34,35]}


# kg_map={-1: {'climate_class': -1,
#             'climate_class_str': 'ND',
#             'description': 'No Data',
#             'colour_code': [255, 255, 255]},
kg_map={0: {'climate_class': 0,
            'climate_class_str': 'S',
            'description': 'sea',
            'colour_code': [0, 0, 0],
            'climate_code': [1, 0, 0, 0, 0, 0],
            'precipitation_code': [0, 0, 0, 0, 0, 0],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 0]},
        1: {'climate_class': 1,
            'climate_class_str': 'Af',
            'description': 'Tropical;rainforest',
            'colour_code': [0, 0, 255],
            'climate_code': [0, 0, 0, 0, 0, 1],
            'precipitation_code': [0, 0, 0, 1, 0, 0],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 0]
            },
        2: {'climate_class': 1,
            'climate_class_str': 'Am',
            'description': 'Tropical;monsoon',
            'colour_code': [0, 120, 255],
            'climate_code': [0, 0, 0, 0, 0, 1],
            'precipitation_code': [1, 0, 0, 0, 0, 0],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 0]
            },
        3: {'climate_class': 1,
            'climate_class_str': 'Aw',
            'description': 'Tropical;savannah',
            'colour_code': [70, 170, 250],
            'climate_code': [0, 0, 0, 0, 0, 1],
            'precipitation_code': [0, 0, 0, 0, 0, 1],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 0]
            },
        4: {'climate_class': 2,
            'climate_class_str': 'BWh',
            'description': 'Arid;desert;hot',
            'colour_code': [255, 0, 0],
            'climate_code': [0, 0, 0, 0, 1, 0],
            'precipitation_code': [0, 0, 0, 0, 0, 1],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 1]
            },
        5: {'climate_class': 2,
            'climate_class_str': 'BWk',
            'description': 'Arid;desert;cold',
            'colour_code': [255, 150, 150],
            'climate_code': [0, 0, 0, 0, 1, 0],
            'precipitation_code': [0, 0, 0, 0, 0, 1],
            'temperature_code': [0, 0, 0, 0, 0, 0, 1, 0]
            },
        6: {'climate_class': 2,
            'climate_class_str': 'BSh',
            'description': 'Arid;steppe;hot',
            'colour_code': [245, 165, 0],
            'climate_code': [0, 0, 0, 0, 1, 0],
            'precipitation_code': [0, 0, 0, 0, 1, 0],
            'temperature_code': [0, 0, 0, 0, 0, 0, 0, 1]
            },
        7: {'climate_class': 2,
            'climate_class_str': 'BSk',
            'description': 'Arid;steppe;cold',
            'colour_code': [255, 220, 100],
            'climate_code': [0, 0, 0, 0, 1, 0],
            'precipitation_code': [0, 0, 0, 0, 1, 0],
            'temperature_code': [0, 0, 0, 0, 0, 0, 1, 0]
            },
        8: {'climate_class': 3,
            'climate_class_str': 'Csa',
            'description': 'Temperate;dry summer;hot summer',
            'colour_code': [255, 255, 0],
            'climate_code': [0, 0, 0, 1, 0, 0],
            'precipitation_code': [0, 0, 0, 0, 1, 0],
            'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
            },
        9: {'climate_class': 3,
            'climate_class_str': 'Csb',
            'description': 'Temperate;dry summer;warm summer',
            'colour_code': [200, 200, 0],
            'climate_code': [0, 0, 0, 1, 0, 0],
            'precipitation_code': [0, 0, 0, 0, 1, 0],
            'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
            },
        10: {'climate_class': 3,
             'climate_class_str': 'Csc',
             'description': 'Temperate;dry summer;cold summer',
             'colour_code': [150, 150, 0],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 0, 0, 0, 1, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        11: {'climate_class': 3,
             'climate_class_str': 'Cwa',
             'description': 'Temperate;dry winter;hot summer',
             'colour_code': [150, 255, 150],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
             },
        12: {'climate_class': 3,
             'climate_class_str': 'Cwb',
             'description': 'Temperate;dry winter;warm summer',
             'colour_code': [100, 200, 100],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
             },
        13: {'climate_class': 3,
             'climate_class_str': 'Cwc',
             'description': 'Temperate;dry winter;cold summer',
             'colour_code': [50, 150, 50],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        14: {'climate_class': 3,
             'climate_class_str': 'Cfa',
             'description': 'Temperate;no dry season;hot summer',
             'colour_code': [200, 255, 80],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
             },
        15: {'climate_class': 3,
             'climate_class_str': 'Cfb',
             'description': 'Temperate;no dry season;warm summer',
             'colour_code': [100, 255, 80],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
             },
        16: {'climate_class': 3,
             'climate_class_str': 'Cfc',
             'description': 'Temperate;no dry season;cold summer',
             'colour_code': [50, 200, 0],
             'climate_code': [0, 0, 0, 1, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        17: {'climate_class': 4,
             'climate_class_str': 'Dsa',
             'description': 'Cold;dry summer;hot summer',
             'colour_code': [255, 0, 255],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 1, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
             },
        18: {'climate_class': 4,
             'climate_class_str': 'Dsb',
             'description': 'Cold;dry summer;warm summer',
             'colour_code': [200, 0, 200],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 1, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
             },
        19: {'climate_class': 4,
             'climate_class_str': 'Dsc',
             'description': 'Cold;dry summer;cold summer',
             'colour_code': [150, 50, 150],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 1, 0, 0, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        20: {'climate_class': 4,
             'climate_class_str': 'Dsd',
             'description': 'Cold;dry summer;very cold winter',
             'colour_code': [150, 100, 150],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 1, 0, 0, 0],
             'temperature_code': [0, 0, 1, 0, 0, 0, 0, 0]
             },
        21: {'climate_class': 4,
             'climate_class_str': 'Dwa',
             'description': 'Cold;dry winter;hot summer',
             'colour_code': [170, 175, 255],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
             },
        22: {'climate_class': 4,
             'climate_class_str': 'Dwb',
             'description': 'Cold;dry winter;warm summer',
             'colour_code': [90, 120, 220],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
             },
        23: {'climate_class': 4,
             'climate_class_str': 'Dwc',
             'description': 'Cold;dry winter;cold summer',
             'colour_code': [75, 80, 180],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        24: {'climate_class': 4,
             'climate_class_str': 'Dwd',
             'description': 'Cold;dry winter;very cold winter',
             'colour_code': [50, 0, 135],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 1, 0, 0, 0, 0],
             'temperature_code': [0, 0, 1, 0, 0, 0, 0, 0]
             },
        25: {'climate_class': 4,
             'climate_class_str': 'Dfa',
             'description': 'Cold;no dry season;hot summer',
             'colour_code': [0, 255, 255],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 0, 0, 1, 0, 0]
             },
        26: {'climate_class': 4,
             'climate_class_str': 'Dfb',
             'description': 'Cold;no dry season;warm summer',
             'colour_code': [55, 200, 255],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 0, 1, 0, 0, 0]
             },
        27: {'climate_class': 4,
             'climate_class_str': 'Dfc',
             'description': 'Cold;no dry season;cold summer',
             'colour_code': [0, 125, 125],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 0, 1, 0, 0, 0, 0]
             },
        28: {'climate_class': 4,
             'climate_class_str': 'Dfd',
             'description': 'Cold;no dry season;very cold winter',
             'colour_code': [0, 70, 95],
             'climate_code': [0, 0, 1, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 1, 0, 0],
             'temperature_code': [0, 0, 1, 0, 0, 0, 0, 0]
             },
        29: {'climate_class': 5,
             'climate_class_str': 'ET',
             'description': 'Polar;tundra',
             'colour_code': [178, 178, 178],
             'climate_code': [0, 1, 0, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 0, 0, 0],
             'temperature_code': [1, 0, 0, 0, 0, 0, 0, 0]
             },
        30: {'climate_class': 5,
             'climate_class_str': 'EF',
             'description': 'Polar;frost',
             'colour_code': [102, 102, 102],
             'climate_code': [0, 1, 0, 0, 0, 0],
             'precipitation_code': [0, 0, 0, 0, 0, 0],
             'temperature_code': [0, 1, 0, 0, 0, 0, 0, 0]
             }}